#DB dev specific
server.servlet.context-path=/market-auction
#spring.datasource.url=jdbc:sqlserver://;serverName=${DB_SERVER_NAME};databaseName=sericultureprd;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=seruser1
#spring.datasource.password=${DB_PASS}
spring.datasource.url=jdbc:sqlserver://;serverName=DSER-LIS.infra.karnataka.gov.in;databaseName=sericultureprd;encrypt=true;trustServerCertificate=true;
spring.datasource.username=seruser1
spring.datasource.password=Seri01@07user1
spring.jpa.show-sql= false
# Custom Properties
# Please ensure you use right options just for dev feasibility everything is allowed, which will not be the case in production.
sericulture.cors.allowed-origins: "*"
sericulture.cors.allowed-methods: "*"
sericulture.cors.max-age: 3000
sericulture.cors.allowed-headers: "*"
sericulture.cors.xposed-headers: "*"
aws.accessKeyId=2OTKFSI6UAHLUCEKRV5Z
aws.secretKey=1Ep3uV43mfSQJXae25+gxrZmLA8xhmYnTGJ8dtYr
aws.region=us-east-1
aws.bucketName=sericulture
aws.host=http://172.31.55.243
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true
#application.arn.prefix=${ARN_PREFIX}
application.arn.prefix=SDBT